import { Link, createFileRoute, notFound } from "@tanstack/react-router";
import { Check, ChevronLeft, Plus } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { FoodImage, QuantityControl } from "@/components/umami";
import { addOns, formatPrice, products } from "@/lib/catalog";
import { useCart } from "@/lib/cart";

export const Route = createFileRoute("/product/$id")({ loader: ({ params }) => { const product = products.find((item) => item.id === params.id); if (!product) throw notFound(); return product; }, head: ({ loaderData }) => ({ meta: [{ title: loaderData ? `${loaderData.name} — UMAMI'S` : "Производот не е пронајден — UMAMI'S" }, { name: "description", content: loaderData?.description ?? "UMAMI производ" }, { property: "og:title", content: loaderData ? `${loaderData.name} — UMAMI'S` : "UMAMI'S" }, { property: "og:description", content: loaderData?.description ?? "UMAMI производ" }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: ProductPage });
function ProductPage() { const product = Route.useLoaderData(); const { addItem } = useCart(); const [quantity,setQuantity]=useState(1); const [selected,setSelected]=useState<string[]>([]); const [added,setAdded]=useState(false); const selectedAddOns=addOns.filter(a=>selected.includes(a.id)); const total=(product.price+selectedAddOns.reduce((s,a)=>s+a.price,0))*quantity; return <div className="mx-auto max-w-7xl px-4 pb-6 pt-5 md:px-6"><Link to="/menu" className="inline-flex items-center gap-1 text-sm font-semibold text-muted-foreground"><ChevronLeft className="size-4"/>Назад кон мени</Link><div className="mt-5 grid gap-6 lg:grid-cols-2 lg:gap-10"><div className="glass aspect-square overflow-hidden rounded-[26px]"><FoodImage src={product.image} position={product.imagePosition} alt={product.name} eager/></div><div className="lg:py-6"><p className="text-xs font-bold uppercase tracking-[0.18em] text-primary">{product.categoryLabel}</p><h1 className="mt-2 font-display text-4xl font-bold leading-none md:text-5xl">{product.name}</h1><p className="mt-4 text-muted-foreground">{product.description}</p><p className="mt-5 font-display text-2xl font-bold">{formatPrice(product.price)}</p><div className="mt-7"><h2 className="font-display text-lg font-bold">Состојки</h2><div className="mt-3 flex flex-wrap gap-2">{product.ingredients.map(i=><span key={i} className="glass-soft rounded-full px-3 py-1.5 text-xs font-semibold">{i}</span>)}</div></div><div className="mt-7"><h2 className="font-display text-lg font-bold">Избери додатоци</h2><div className="mt-3 space-y-2">{addOns.map(a=><label key={a.id} className="glass-soft flex cursor-pointer items-center gap-3 rounded-xl p-3"><input type="checkbox" className="sr-only" checked={selected.includes(a.id)} onChange={()=>setSelected(s=>s.includes(a.id)?s.filter(id=>id!==a.id):[...s,a.id])}/><span className={`grid size-5 place-items-center rounded-md border ${selected.includes(a.id)?"bg-primary text-primary-foreground":"bg-card"}`}>{selected.includes(a.id)&&<Check className="size-3"/>}</span><span className="flex-1 text-sm font-semibold">{a.label}</span><span className="text-sm text-muted-foreground">+{formatPrice(a.price)}</span></label>)}</div></div><div className="mt-7 flex items-center gap-3"><QuantityControl value={quantity} onChange={setQuantity}/><Button size="lg" className="flex-1" onClick={()=>{addItem(product,quantity,selectedAddOns);setAdded(true);setTimeout(()=>setAdded(false),1500)}}>{added?<><Check/>Додадено</>:<><Plus/>ДОДАЈ · {formatPrice(total)}</>}</Button></div></div></div></div>; }