import { Link } from "@tanstack/react-router";
import { Check, ChevronRight, Leaf, Menu, Minus, Phone, Plus, ShoppingBag, Trash2, X, Zap } from "lucide-react";
import { useState, type ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { cn } from "@/lib/utils";
import { addOns, formatPrice, type Product } from "@/lib/catalog";
import { useCart, type CartLine } from "@/lib/cart";

export function FoodImage({ src, position, alt, className, eager = false }: { src: string; position: string; alt: string; className?: string; eager?: boolean }) {
  const isSheet = position !== "center";
  return <img src={src} alt={alt} width={1200} height={1200} loading={eager ? "eager" : "lazy"} className={cn("h-full w-full object-cover", isSheet && "scale-[2]", className)} style={{ objectPosition: position, transformOrigin: position }} />;
}

export function SiteHeader() {
  const [open, setOpen] = useState(false); const { count } = useCart();
  return <header className="sticky top-0 z-40 mx-auto w-full max-w-7xl px-3 pt-3 md:px-6"><div className="glass grid h-16 grid-cols-[minmax(0,1fr)_auto] items-center rounded-[22px] px-3 sm:flex sm:justify-between sm:px-4">
    <Link to="/" className="flex min-w-0 items-center gap-2.5"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-primary font-display text-sm font-bold text-primary-foreground">U</span><span className="truncate font-display text-[17px] font-bold">UMAMI<span className="text-primary">'S</span></span></Link>
    <nav className="hidden items-center gap-7 text-sm font-semibold md:flex"><Link to="/menu" activeProps={{ className: "text-primary" }}>Мени</Link><a href="/#about">За нас</a><a href="#contact">Контакт</a></nav>
    <div className="flex shrink-0 items-center gap-2"><Button asChild variant="glass" size="icon" className="relative rounded-full"><Link to="/cart" aria-label="Кошничка"><ShoppingBag />{count > 0 && <span className="absolute -right-1 -top-1 grid size-5 place-items-center rounded-full bg-destructive text-[10px] font-bold text-destructive-foreground">{count}</span>}</Link></Button><Button variant="glass" size="icon" className="rounded-full md:hidden" onClick={() => setOpen(!open)} aria-label="Отвори мени">{open ? <X /> : <Menu />}</Button></div>
  </div>{open && <nav className="glass mt-2 grid gap-1 rounded-2xl p-2 md:hidden"><Link to="/menu" onClick={() => setOpen(false)} className="rounded-xl px-4 py-3 font-semibold">Мени</Link><a href="/#about" onClick={() => setOpen(false)} className="rounded-xl px-4 py-3 font-semibold">За нас</a><a href="#contact" onClick={() => setOpen(false)} className="rounded-xl px-4 py-3 font-semibold">Контакт</a></nav>}</header>;
}

export function SiteFooter() { return <footer id="contact" className="mx-auto max-w-7xl px-4 pb-24 pt-12 md:px-6"><div className="glass rounded-3xl p-6 md:flex md:items-end md:justify-between"><div><div className="flex items-center gap-2.5"><span className="grid size-8 place-items-center rounded-full bg-primary font-display text-sm font-bold text-primary-foreground">U</span><span className="font-display font-bold">UMAMI'S SUSHI &amp; BURRITO</span></div><p className="mt-3 text-sm text-muted-foreground">Битола, Северна Македонија</p><a href="tel:+38978720777" className="mt-3 inline-flex items-center gap-2 text-sm font-semibold text-primary"><Phone className="size-4" />+389 78 720 777</a></div><div className="mt-6 flex gap-5 text-sm font-semibold text-muted-foreground md:mt-0"><Link to="/menu">Мени</Link><a href="/#about">За нас</a><a href="#contact">Контакт</a></div></div></footer>; }

export function CategoryCard({ category }: { category: { slug: string; label: string; count: number; image: string; imagePosition: string } }) { return <Link to={`/menu/${category.slug}` as "/menu/sushi"} className="glass group w-32 shrink-0 snap-start rounded-2xl p-2.5 transition-transform hover:-translate-y-1 md:w-auto"><div className="aspect-square overflow-hidden rounded-xl"><FoodImage src={category.image} position={category.imagePosition} alt={category.label} className="transition-transform duration-500 group-hover:scale-[2.05]" /></div><p className="mt-2 font-display text-sm font-semibold">{category.label}</p><p className="text-[11px] text-muted-foreground">{category.count} ставки</p></Link>; }

export function ProductCard({ product }: { product: Product }) { const { addItem } = useCart(); return <article className="glass group flex gap-3 rounded-2xl p-3 md:flex-col"><Link to="/product/$id" params={{ id: product.id }} className="size-28 shrink-0 overflow-hidden rounded-xl md:aspect-[4/3] md:size-auto"><FoodImage src={product.image} position={product.imagePosition} alt={product.name} className="transition-transform duration-500 group-hover:scale-[2.05]" /></Link><div className="flex min-w-0 flex-1 flex-col">{product.bestseller && <span className="mb-1 self-start rounded-full bg-destructive/10 px-2 py-0.5 text-[9px] font-bold uppercase text-destructive">Бестселер</span>}<Link to="/product/$id" params={{ id: product.id }} className="font-display text-[15px] font-semibold leading-tight">{product.name}</Link><p className="mt-1 line-clamp-2 text-xs leading-snug text-muted-foreground">{product.description}</p><div className="mt-auto flex items-center justify-between pt-2"><span className="font-display font-bold">{formatPrice(product.price)}</span><Button size="icon" className="rounded-full" onClick={() => addItem(product)} aria-label={`Додај ${product.name}`}><Plus /></Button></div></div></article>; }

export function PageIntro({ eyebrow = "UMAMI'S МЕНИ", title, description }: { eyebrow?: string; title: string; description: string }) { return <section className="mx-auto max-w-7xl px-4 pb-7 pt-12 md:px-6 md:pt-16"><p className="text-xs font-bold uppercase tracking-[0.18em] text-primary">{eyebrow}</p><h1 className="mt-2 max-w-3xl font-display text-4xl font-bold leading-none md:text-6xl">{title}</h1><p className="mt-4 max-w-2xl text-sm leading-relaxed text-muted-foreground md:text-base">{description}</p></section>; }

export function MenuGrid({ items }: { items: Product[] }) { return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{items.map((item) => <ProductCard key={item.id} product={item} />)}</div>; }

export function QuantityControl({ value, onChange }: { value: number; onChange: (value: number) => void }) { return <div className="glass-soft grid grid-cols-[40px_44px_40px] items-center rounded-full p-1"><Button variant="ghost" size="icon" className="rounded-full" onClick={() => onChange(Math.max(1, value - 1))} aria-label="Намали"><Minus /></Button><span className="text-center font-bold tabular-nums">{value}</span><Button variant="ghost" size="icon" className="rounded-full" onClick={() => onChange(value + 1)} aria-label="Зголеми"><Plus /></Button></div>; }

export function ProductCustomization({ selected, onChange }: { selected: string[]; onChange: (selected: string[]) => void }) { return <div><h2 className="font-display text-lg font-bold">Избери додатоци</h2><div className="mt-3 space-y-2">{addOns.map((addOn) => <label key={addOn.id} className="glass-soft flex cursor-pointer items-center gap-3 rounded-xl p-3"><input type="checkbox" className="sr-only" checked={selected.includes(addOn.id)} onChange={() => onChange(selected.includes(addOn.id) ? selected.filter((id) => id !== addOn.id) : [...selected, addOn.id])}/><span className={cn("grid size-5 place-items-center rounded-md border", selected.includes(addOn.id) ? "bg-primary text-primary-foreground" : "bg-card")}>{selected.includes(addOn.id) && <Check className="size-3"/>}</span><span className="flex-1 text-sm font-semibold">{addOn.label}</span><span className="text-sm text-muted-foreground">+{formatPrice(addOn.price)}</span></label>)}</div></div>; }

export function Modal({ open, onOpenChange, title, description, children }: { open: boolean; onOpenChange: (open: boolean) => void; title: string; description?: string; children: ReactNode }) { return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="glass rounded-3xl"><DialogHeader><DialogTitle className="font-display">{title}</DialogTitle>{description && <DialogDescription>{description}</DialogDescription>}</DialogHeader>{children}</DialogContent></Dialog>; }

export function CartItem({ line }: { line: CartLine }) { const { updateQuantity, removeItem } = useCart(); const unit = line.product.price + line.addOns.reduce((sum, addOn) => sum + addOn.price, 0); return <article className="glass grid grid-cols-[88px_minmax(0,1fr)] gap-3 rounded-2xl p-3 sm:grid-cols-[112px_minmax(0,1fr)_auto]"><div className="aspect-square overflow-hidden rounded-xl"><FoodImage src={line.product.image} position={line.product.imagePosition} alt={line.product.name} /></div><div className="min-w-0"><h3 className="font-display font-semibold leading-tight">{line.product.name}</h3><p className="mt-1 text-xs text-muted-foreground">{line.addOns.length ? line.addOns.map((a) => a.label).join(", ") : "Без додатоци"}</p><p className="mt-2 font-bold">{formatPrice(unit * line.quantity)}</p><button onClick={() => removeItem(line.key)} className="mt-2 inline-flex items-center gap-1 text-xs font-semibold text-destructive"><Trash2 className="size-3.5" />Отстрани</button></div><div className="col-span-2 sm:col-span-1"><QuantityControl value={line.quantity} onChange={(value) => updateQuantity(line.key, value)} /></div></article>; }

export function Benefit({ icon, title, body }: { icon: ReactNode; title: string; body: string }) { return <div className="glass rounded-2xl p-4"><div className="grid size-10 place-items-center rounded-xl bg-primary/10 text-primary">{icon}</div><p className="mt-3 font-display text-sm font-semibold">{title}</p><p className="mt-1 text-xs text-muted-foreground">{body}</p></div>; }
export const benefitIcons = { fresh: <Leaf className="size-5" />, fast: <Zap className="size-5" />, pickup: <Check className="size-5" />, delivery: <ChevronRight className="size-5" /> };